services:
  api:
    container_name: steamshark-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-:8800}
      - DB_PATH=${DB_PATH:-/app/data/steamshark.db}
    volumes:
      - ./db:/app/data
    ports:
      - 8800:8800
    healthcheck:
      test: ["CMD", "wget", "-q", "http://localhost:8800/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

#volumes:
#  steamshark_db: