services:
  api:
    container_name: steamshark-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_PATH=${DB_PATH}
    volumes:
      # Persist the SQLite DB outside the container
      - steamshark_db:/app/databases
    expose:
      - 8800

volumes:
  steamshark_db: